In [ ]:
numerical python

complex calculation


list 
tuple 

numpy

In [ ]:
numpy is faster that list and tuple
built by using c programming
by using we can create n-dim
relation algebric cal we are using numpy

In [1]:
import numpy as np

In [8]:
a = np.array([10,30,60])

In [9]:
a

array([10, 30, 60])

In [10]:
type(a)

numpy.ndarray

In [5]:
a.ndim

1

In [11]:
a

array([10, 30, 60])

In [15]:
a[2]

60

In [16]:
a.ndim

1

In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a.ndim

2

In [23]:
t = (10,20,30)

In [24]:
type(t)

tuple

In [29]:
a = np.array((10,20,30))

In [26]:
type(a)

numpy.ndarray

In [27]:
a = [10,20,30]

In [28]:
type(a)

list

In [30]:
a

array([10, 20, 30])

In [31]:
a = np.array((1,2,34))

In [32]:
a

array([ 1,  2, 34])

In [42]:
a = np.array(['1','2','3'],dtype=int)

In [43]:
a

array([1, 2, 3])

In [71]:
a = np.array([1,2,3],dtype='int32')

In [68]:
a

array([1, 2, 3], dtype=int16)

In [69]:
a.size

3

In [64]:
len(a)

3

In [74]:
a.itemsize

4

In [77]:
a = np.array([1,2,3],dtype='int8')

In [78]:
a.itemsize

1

In [79]:
a.shape

(3,)

In [81]:
a = np.array([[3,5,7],[56,78,4]])

In [82]:
a.shape

(2, 3)

In [83]:
2*3

6

In [ ]:
1,6
3,2
6,1


In [84]:
a.reshape(6,1)

array([[ 3],
       [ 5],
       [ 7],
       [56],
       [78],
       [ 4]])

In [87]:
a.reshape(1,6)

array([[ 3,  5,  7, 56, 78,  4]])

In [88]:
a

array([[ 3,  5,  7],
       [56, 78,  4]])

In [89]:
a.ndim

2

In [90]:
#list range

In [91]:
#to generate seq of number

In [ ]:
numpy array 


arange

In [92]:
a  = np.arange(10)

In [93]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
a = np.arange(1,10,3)

In [95]:
a

array([1, 4, 7])

In [96]:
a.ndim

1

In [98]:
a.reshape(3,1).ndim

2

In [99]:
a = np.empty([3,4],dtype=int)

In [100]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [101]:
a = np.ones([4,4])

In [102]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [105]:
a = np.zeros(5,dtype=int)

In [107]:
a.ndim

1

In [115]:
a = np.array([[[1,2,3],[100,200,300]],[[1,2,3],[100,200,300]]])

In [117]:
a.ndim

3

In [118]:
p = [1,2,3]

In [119]:
a = np.array(p,dtype=int)

In [120]:
a

array([1, 2, 3])

In [121]:
p = [(1,2,3),(4,5,6)]

In [122]:
p

[(1, 2, 3), (4, 5, 6)]

In [123]:
a = np.array(p)

In [124]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
a = np.arange(10)

In [126]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
a = np.linspace(10,20,4)

In [136]:
a

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [137]:
a = np.linspace(10,20,4,endpoint=False)

In [138]:
a

array([10. , 12.5, 15. , 17.5])

In [132]:
.25

2.0

In [134]:
11/

2.75

In [ ]:
# doubt linespace

In [146]:
a = np.linspace(1,100,5)

In [147]:
a

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [ ]:
1 2 3 4 5 6 7 8 9 10

In [141]:
10/4

2.5

In [148]:
99/5

19.8

In [149]:
101/5

20.2

In [150]:
p = 'abc'

In [153]:
a = np.linspace(1,10,3)

In [154]:
a

array([ 1. ,  5.5, 10. ])

In [156]:
(10-1)/2

4.5

In [157]:
import pandas as pd

In [158]:
import requests

In [159]:
r = requests.get("https://api.sampleapis.com/fakebank/accounts")

In [162]:
df = pd.read_json(r.content)

In [163]:
df

transactionDate                    description        category   debit  \
0        2015-12-31              All Purpose Spray  Other Services  100.84   
1        2016-01-02   Dr. FlimFlam's miracle cream     Health Care   59.99   
2        2016-01-05                 Planet Express  Other Services   14.95   
3        2016-01-08                        MomCorp  Payment/Credit     NaN   
4        2016-01-10               30th Century Fox     Merchandise   20.98   
..              ...                            ...             ...     ...   
182      2016-12-23                 Admiral Crunch     Merchandise  183.87   
183      2016-12-23             Ronco Record Vault     Merchandise   85.00   
184      2016-12-24  Mom's Old-Fashioned Robot Oil  Gas/Automotive   38.27   
185      2016-12-29                 Admiral Crunch     Merchandise   87.94   
186      2016-12-30                  Bachelor Chow          Dining    7.41   

     credit   id  
0       NaN    1  
1       NaN    2  
2       NaN    3  
3    175.78    4  
4       NaN    5  
..      ...  ...  
182     NaN  183  
183     NaN  184  
184     NaN  185  
185     NaN  186  
186     NaN  187  

[187 rows x 6 columns]

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape

(2, 3)

In [5]:
a = np.arange(10)

In [6]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a[1:6:2]

array([1, 3, 5])

In [10]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

In [11]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [12]:
a.shape

(3, 3)

In [16]:
a[1:,0:2]

array([[3, 4],
       [4, 5]])

In [17]:
a[0:2,0:2]

array([[1, 2],
       [3, 4]])

In [ ]:
[1, 2, 3],
[3, 4, 5],
[4, 5, 6]

In [20]:
a[0:,0:3:2]

array([[1, 3],
       [3, 5],
       [4, 6]])

In [21]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [22]:
a[0:,0:3:2]

array([[1, 3],
       [3, 5],
       [4, 6]])

In [ ]:
#Broadcasting

In [23]:
a = np.array([1,2,3])

In [24]:
a

array([1, 2, 3])

In [25]:
a+2

array([3, 4, 5])

In [26]:
a

array([1, 2, 3])

In [28]:
b = np.array([4,5,6])

In [29]:
a+b

array([5, 7, 9])

In [41]:
a = np.array([[1,2,3],[4,5,6]])

In [46]:
b = np.array([100,200,900])

In [47]:
a+b

array([[101, 202, 903],
       [104, 205, 906]])

In [33]:
a = np.array([[1,2,3],[4,5,6]])

In [34]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
b = np.array([[10,20,30],[40,50,60]])

In [37]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a+b

array([[11, 22, 33],
       [44, 55, 66]])

In [40]:
a*b

array([[ 10,  40,  90],
       [160, 250, 360]])

In [48]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
b

array([100, 200, 900])

In [51]:
b = np.array([[10,20,30],[40,50,60]])

In [52]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [54]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [56]:
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [57]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [59]:
b = b.reshape(3,2)

In [60]:
np.dot(a,b)

array([[220, 280],
       [490, 640]])

In [61]:
a = np.arange(8).reshape(2,4)

In [62]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [64]:
a.flatten() # imp

array([0, 1, 2, 3, 4, 5, 6, 7])

In [71]:
np.random.random((3,3))

array([[0.6689016 , 0.90790701, 0.08189569],
       [0.60004121, 0.50112428, 0.62898885],
       [0.1090246 , 0.68602436, 0.24071259]])

In [67]:
np.random.randint(0,10,(3,3))

array([[5, 6, 6],
       [2, 3, 8],
       [9, 2, 4]])

In [68]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.random.normal(0,1,(3,3))

array([[-1.19022424,  0.19018249, -0.42073937],
       [-1.16850586,  0.94376053,  1.56315277],
       [-0.86113201, -0.23973165,  0.44980263]])

In [75]:
a = np.array([1,4,6,8,3,9,4,3])

In [77]:
np.where(a<5)

(array([0, 1, 4, 6, 7], dtype=int64),)

In [78]:
np.where(a)

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)

In [79]:
a

array([1, 4, 6, 8, 3, 9, 4, 3])

In [80]:
a = np.array([1,2,0,4,5])

In [81]:
find = np.where(a>2)

In [82]:
find

(array([3, 4], dtype=int64),)

In [83]:
#where function prsent index return

In [84]:
a = np.array([1,4,6,8,3,9,4,3])

In [85]:
np.where(a>5)

(array([2, 3, 5], dtype=int64),)

In [86]:
a[2]

6

In [108]:
for i in a:
    
    if a[i] in list(np.where(a>5)[0]):
        print(a[i])

3


IndexError: index 8 is out of bounds for axis 0 with size 8

In [92]:
list(np.where(a>5))

[array([2, 3, 5], dtype=int64)]

[2, 3, 5]

In [106]:
5 in list(np.where(a>5)[0]) 

True

In [111]:
for i in list(np.where(a>5)[0]):
    print(a[i],end=' ')

6 8 9 

In [112]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [113]:
(20-10)/(5-1)

2.5